[package]
name = "wifi-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
pcap = "1.0"
nix = "0.26"
libc = "0.2"
colored = "2.0"
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
socket2 = "0.5"
raw-socket = "0.2" 