default_host_triple = "x86_64-unknown-linux-gnu"
default_toolchain = "stable"
profile = "default"
version = "12"

[telemetry]
disabled = false
verbose = false

[proxy]
proxy = "none"
proxy_ssh = "none" 